import { ProfileTheme, CardTemplate } from '../types';

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    id: 'official_bestexperts',
    name: 'BEST EXPERTS-GROUP (Charte Officielle)',
    category: 'company_official',
    categoryLabel: 'Charte Entreprise',
    description: 'Modèle officiel certifié pour l’ensemble des collaborateurs et consultants du groupe.',
    bestFor: 'Tous les collaborateurs, direction, auditeurs et consultants',
    badge: 'Charte Officielle',
    isOfficial: true,
    recommendedIndustry: 'Conseil, Audit & Ingénierie Financière',
    tags: ['Entreprise', 'Certifié', 'Bleu Marine', 'Équipe'],
    popularityScore: 100,
    theme: {
      preset: 'official_bestexperts',
      primaryColor: '#1e3a8a',
      secondaryColor: '#3b82f6',
      accentColor: '#f59e0b',
      backgroundColor: '#0a0f1d',
      cardBackground: '#131b2e',
      textColor: '#f8fafc',
      mutedTextColor: '#94a3b8',
      borderRadius: 'lg',
      buttonStyle: 'rounded',
      fontFamily: 'Plus Jakarta Sans',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'mesh',
      darkMode: true,
    },
  },
  {
    id: 'corporate_prestige',
    name: 'Direction & Executive Prestige',
    category: 'executive',
    categoryLabel: 'Direction & C-Level',
    description: 'Bleu nuit impérial, accents dorés brossés et typographie statutaire pour dirigeants.',
    bestFor: 'Directeurs Généraux, Présidents, Membres du Comex & Fondateurs',
    badge: 'Statutaire',
    recommendedIndustry: 'Direction Générale, Holdings & Banques d\'Affaires',
    tags: ['Direction', 'Or', 'Luxe', 'Statutaire'],
    popularityScore: 98,
    theme: {
      preset: 'corporate_prestige',
      primaryColor: '#0f2042',
      secondaryColor: '#1e3a8a',
      accentColor: '#d97706',
      backgroundColor: '#070c18',
      cardBackground: '#0f172a',
      textColor: '#f8fafc',
      mutedTextColor: '#cbd5e1',
      borderRadius: 'lg',
      buttonStyle: 'rounded',
      fontFamily: 'Plus Jakarta Sans',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'mesh',
      darkMode: true,
    },
  },
  {
    id: 'obsidian_boardroom',
    name: 'Obsidian Noir Carbone',
    category: 'executive',
    categoryLabel: 'Direction & C-Level',
    description: 'Finition noir mat profond, titane brossé et contrastes chirurgicaux.',
    bestFor: 'Avocats d’Affaires, Associés M&A, VC & Serial Entrepreneurs',
    badge: 'Haute Précision',
    recommendedIndustry: 'Cabinets Juridiques, Capital Risque & Fusions-Acquisitions',
    tags: ['Noir Mat', 'Minimal', 'Carbone', 'Haut De Gamme'],
    popularityScore: 95,
    theme: {
      preset: 'obsidian_boardroom',
      primaryColor: '#000000',
      secondaryColor: '#27272a',
      accentColor: '#10b981',
      backgroundColor: '#09090b',
      cardBackground: '#18181b',
      textColor: '#fafafa',
      mutedTextColor: '#a1a1aa',
      borderRadius: 'xl',
      buttonStyle: 'rounded',
      fontFamily: 'Outfit',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'grid',
      darkMode: true,
    },
  },
  {
    id: 'emerald_wealth',
    name: 'Émeraude Private Wealth',
    category: 'finance_consulting',
    categoryLabel: 'Finance & Conseil',
    description: 'Vert émeraude profond d’inspiration banques privées suisses et gestion d’actifs.',
    bestFor: 'Family Offices, Banquiers Privés, Gestionnaires de Patrimoine & Fiscalistes',
    badge: 'Prestige Finance',
    recommendedIndustry: 'Gestion d’Actifs, Patrimoine & Assurance Haut de Gamme',
    tags: ['Émeraude', 'Banque Privée', 'Patrimoine', 'Luxe'],
    popularityScore: 94,
    theme: {
      preset: 'emerald_wealth',
      primaryColor: '#064e3b',
      secondaryColor: '#047857',
      accentColor: '#10b981',
      backgroundColor: '#022c22',
      cardBackground: '#064e3b',
      textColor: '#ecfdf5',
      mutedTextColor: '#a7f3d0',
      borderRadius: 'lg',
      buttonStyle: 'rounded',
      fontFamily: 'Plus Jakarta Sans',
      headerLayout: 'split_modern',
      coverImageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'mesh',
      darkMode: true,
    },
  },
  {
    id: 'sapphire_consulting',
    name: 'Saphir Conseil Stratégique',
    category: 'finance_consulting',
    categoryLabel: 'Finance & Conseil',
    description: 'Design clair et structuré inspiré des cabinets de conseil Big 4 et McKinsey/BCG.',
    bestFor: 'Consultants en Stratégie, Auditeurs Financiers, Experts Comptables',
    badge: 'Recommandé B2B',
    recommendedIndustry: 'Cabinet de Conseil, Audit, Expertise Comptable & Transformation',
    tags: ['Clair', 'B2B', 'Corporate', 'Audit'],
    popularityScore: 92,
    theme: {
      preset: 'sapphire_consulting',
      primaryColor: '#1e40af',
      secondaryColor: '#3b82f6',
      accentColor: '#2563eb',
      backgroundColor: '#f8fafc',
      cardBackground: '#ffffff',
      textColor: '#0f172a',
      mutedTextColor: '#64748b',
      borderRadius: 'md',
      buttonStyle: 'rounded',
      fontFamily: 'Inter',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'none',
      darkMode: false,
    },
  },
  {
    id: 'cyber_fintech',
    name: 'Cyber Cyan & FinTech',
    category: 'tech_saas',
    categoryLabel: 'Tech & Startups',
    description: 'Teinte cyan électrisante, police néo-grotesque et découpe ultra-moderne.',
    bestFor: 'CTO, Ingénieurs FinTech, Développeurs Web3 & Cloud Architects',
    badge: 'Tech Tendance',
    recommendedIndustry: 'FinTech, SaaS B2B, Cybersécurité & Cloud Computing',
    tags: ['Cyan', 'Cyber', 'FinTech', 'SaaS'],
    popularityScore: 96,
    theme: {
      preset: 'cyber_fintech',
      primaryColor: '#0891b2',
      secondaryColor: '#06b6d4',
      accentColor: '#22d3ee',
      backgroundColor: '#030712',
      cardBackground: '#111827',
      textColor: '#f9fafb',
      mutedTextColor: '#9ca3af',
      borderRadius: 'sm',
      buttonStyle: 'sharp',
      fontFamily: 'Space Grotesk',
      headerLayout: 'minimalist',
      patternOverlay: 'grid',
      darkMode: true,
    },
  },
  {
    id: 'aurora_ai',
    name: 'Aurora IA & DeepTech',
    category: 'tech_saas',
    categoryLabel: 'Tech & Startups',
    description: 'Violet ultraviolet futuriste et dégradé subtil pour entreprises d’IA et de logiciels.',
    bestFor: 'Fondateurs Startups, Product Designers, IA Researchers & Growth Leaders',
    badge: 'Innovation',
    recommendedIndustry: 'Intelligence Artificielle, Logiciels SaaS & Scale-ups',
    tags: ['IA', 'Violet', 'DeepTech', 'Startup'],
    popularityScore: 97,
    theme: {
      preset: 'aurora_ai',
      primaryColor: '#581c87',
      secondaryColor: '#7c3aed',
      accentColor: '#f43f5e',
      backgroundColor: '#120726',
      cardBackground: '#1e0f3d',
      textColor: '#faf5ff',
      mutedTextColor: '#d8b4fe',
      borderRadius: 'xl',
      buttonStyle: 'pill',
      fontFamily: 'Outfit',
      headerLayout: 'centered_card',
      coverImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'dots',
      darkMode: true,
    },
  },
  {
    id: 'minimal_mono',
    name: 'Minimaliste Ardoise Pure',
    category: 'tech_saas',
    categoryLabel: 'Tech & Startups',
    description: 'Une lisibilité sans compromis, contrastes nets et élégance suisse épurée.',
    bestFor: 'Développeurs, Architectes Logiciels, Chercheurs & Designers UI/UX',
    badge: 'Épuré',
    recommendedIndustry: 'Ingénierie Logicielle, Électronique & R&D',
    tags: ['Minimaliste', 'Neutre', 'Monochrome', 'Clair'],
    popularityScore: 91,
    theme: {
      preset: 'minimal_mono',
      primaryColor: '#0f172a',
      secondaryColor: '#475569',
      accentColor: '#2563eb',
      backgroundColor: '#f8fafc',
      cardBackground: '#ffffff',
      textColor: '#0f172a',
      mutedTextColor: '#64748b',
      borderRadius: 'md',
      buttonStyle: 'rounded',
      fontFamily: 'Inter',
      headerLayout: 'minimalist',
      patternOverlay: 'none',
      darkMode: false,
    },
  },
  {
    id: 'avant_garde_coral',
    name: 'Studio Corail & Avant-Garde',
    category: 'creative_agency',
    categoryLabel: 'Créatif & Agences',
    description: 'Teintes terracotta et corail énergiques avec typographie éditoriale raffinée.',
    bestFor: 'Directeurs Artistiques, Fondateurs d’Agences de Communication & Médias',
    badge: 'Créatif Populaire',
    recommendedIndustry: 'Agences de Création, Publicité, Médias & Production Audiovisuelle',
    tags: ['Corail', 'Studio', 'Créatif', 'Design'],
    popularityScore: 89,
    theme: {
      preset: 'avant_garde_coral',
      primaryColor: '#ea580c',
      secondaryColor: '#f97316',
      accentColor: '#fbbf24',
      backgroundColor: '#fffbeb',
      cardBackground: '#ffffff',
      textColor: '#451a03',
      mutedTextColor: '#92400e',
      borderRadius: 'xl',
      buttonStyle: 'pill',
      fontFamily: 'Outfit',
      headerLayout: 'split_modern',
      coverImageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'dots',
      darkMode: false,
    },
  },
  {
    id: 'editorial_warmth',
    name: 'Éditorial Warm & Architecture',
    category: 'creative_agency',
    categoryLabel: 'Créatif & Agences',
    description: 'Nuances chaudes de sable et lin, style éditorial pour l’immobilier de prestige et l’architecture.',
    bestFor: 'Architectes, Décorateurs d’Intérieur, Galeries d’Art & Immobilier de Luxe',
    badge: 'Élégant',
    recommendedIndustry: 'Architecture, Immobilier Haut de Gamme & Design d’Espace',
    tags: ['Sable', 'Architecture', 'Éditorial', 'Chaleureux'],
    popularityScore: 88,
    theme: {
      preset: 'editorial_warmth',
      primaryColor: '#78350f',
      secondaryColor: '#92400e',
      accentColor: '#d97706',
      backgroundColor: '#fefce8',
      cardBackground: '#ffffff',
      textColor: '#451a03',
      mutedTextColor: '#78350f',
      borderRadius: 'lg',
      buttonStyle: 'rounded',
      fontFamily: 'Plus Jakarta Sans',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'none',
      darkMode: false,
    },
  },
  {
    id: 'eco_botanical',
    name: 'BioTech Éco-Transition',
    category: 'health_eco',
    categoryLabel: 'Santé, RSE & BioTech',
    description: 'Teintes sauge et forêt apaisantes, valorisant les démarches RSE, énergie et climat.',
    bestFor: 'Directeurs RSE, Ingénieurs Énergie Renouvelable, Fondateurs ClimatTech',
    badge: 'RSE & Impact',
    recommendedIndustry: 'RSE, Énergies Vertes, Agronomie Durable & Écologie',
    tags: ['Vert Forêt', 'RSE', 'Climat', 'BioTech'],
    popularityScore: 90,
    theme: {
      preset: 'eco_botanical',
      primaryColor: '#166534',
      secondaryColor: '#15803d',
      accentColor: '#84cc16',
      backgroundColor: '#f0fdf4',
      cardBackground: '#ffffff',
      textColor: '#14532d',
      mutedTextColor: '#166534',
      borderRadius: 'xl',
      buttonStyle: 'pill',
      fontFamily: 'Plus Jakarta Sans',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'mesh',
      darkMode: false,
    },
  },
  {
    id: 'clinical_pure',
    name: 'Médical & Clinique Pure',
    category: 'health_eco',
    categoryLabel: 'Santé, RSE & BioTech',
    description: 'Bleu médical rassurant, blanc immaculé et organisation claire des coordonnées d’urgence.',
    bestFor: 'Chirurgiens, Médecins Spécialistes, Cliniques & Laboratoires Pharmaceutiques',
    badge: 'Médical Certifié',
    recommendedIndustry: 'Santé, Cliniques, Pharmacie, Dentaire & Laboratoires',
    tags: ['Santé', 'Médical', 'Bleu', 'Clair'],
    popularityScore: 87,
    theme: {
      preset: 'clinical_pure',
      primaryColor: '#0284c7',
      secondaryColor: '#0ea5e9',
      accentColor: '#38bdf8',
      backgroundColor: '#f0f9ff',
      cardBackground: '#ffffff',
      textColor: '#0c4a6e',
      mutedTextColor: '#0369a1',
      borderRadius: 'lg',
      buttonStyle: 'rounded',
      fontFamily: 'Inter',
      headerLayout: 'cover_avatar',
      coverImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'none',
      darkMode: false,
    },
  },
  {
    id: 'gold_vip_concierge',
    name: 'VIP Gold Conciergerie',
    category: 'luxury_vip',
    categoryLabel: 'Luxe & Événementiel',
    description: 'Or royal poli et fond noir caviar pour l’accueil de personnalités et clients privilégiés.',
    bestFor: 'Directeurs d’Hôtels 5 Étoiles, Concierges Clefs d’Or, Événements VIP',
    badge: 'Ultra Luxe',
    recommendedIndustry: 'Hôtellerie de Luxe, Salons Privés, Aviation Privée & Yachts',
    tags: ['Or', 'VIP', 'Luxe', 'Noir & Or'],
    popularityScore: 96,
    theme: {
      preset: 'gold_vip_concierge',
      primaryColor: '#b45309',
      secondaryColor: '#d97706',
      accentColor: '#fbbf24',
      backgroundColor: '#0c0a09',
      cardBackground: '#1c1917',
      textColor: '#fef3c7',
      mutedTextColor: '#d97706',
      borderRadius: 'md',
      buttonStyle: 'sharp',
      fontFamily: 'Outfit',
      headerLayout: 'centered_card',
      coverImageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      patternOverlay: 'mesh',
      darkMode: true,
    },
  },
];

// Helper record for fast lookup and legacy compatibility
const baseThemePresets: Record<string, { name: string; description: string; theme: ProfileTheme }> = 
  CARD_TEMPLATES.reduce((acc, tpl) => {
    acc[tpl.id] = {
      name: tpl.name,
      description: tpl.description,
      theme: tpl.theme,
    };
    return acc;
  }, {} as Record<string, { name: string; description: string; theme: ProfileTheme }>);

// Explicit aliases for legacy theme keys
const LEGACY_ALIASES: Record<string, string> = {
  corporate_navy: 'official_bestexperts',
  emerald_luxe: 'emerald_wealth',
  slate_minimal: 'minimal_mono',
  obsidian_dark: 'obsidian_boardroom',
  sunset_violet: 'aurora_ai',
  rose_gold: 'avant_garde_coral',
  cyber_neon: 'cyber_fintech',
  warm_editorial: 'editorial_warmth',
};

Object.entries(LEGACY_ALIASES).forEach(([legacyKey, targetKey]) => {
  if (baseThemePresets[targetKey]) {
    baseThemePresets[legacyKey] = baseThemePresets[targetKey];
  }
});

// Safe Proxy to prevent any undefined error on THEME_PRESETS.<any_key>
const defaultFallback = baseThemePresets.official_bestexperts || {
  name: 'Charte Officielle',
  description: 'Thème standard',
  theme: CARD_TEMPLATES[0].theme,
};

export const THEME_PRESETS: Record<string, { name: string; description: string; theme: ProfileTheme }> = new Proxy(baseThemePresets, {
  get(target, prop: string) {
    if (prop in target) {
      return target[prop];
    }
    return defaultFallback;
  }
});

